# Generated by Django 3.0.5 on 2020-04-17 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_auto_20200416_0821'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrudOrder',
            fields=[
            ],
            options={
                'verbose_name': 'զակազ թեստ',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('client.order',),
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'permissions': (('read_item', 'Can read item'),)},
        ),
        migrations.RemoveField(
            model_name='imagegroup',
            name='delivery',
        ),
        migrations.AddField(
            model_name='order',
            name='delivery',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
