# Generated by Django 2.2.2 on 2020-05-14 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_auto_20200417_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='path',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='imagegroup',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_image', to='client.Order'),
        ),
    ]
